---
- name: configure access vlan
  hosts: access
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco

  tasks:
    - name: Create VLANS
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - vlan 10
          - vlan 20
          - vlan 30
          - vlan 40

      register: print_output
    -  debug: var=print_output
